services:
  gitlab-ai-agent:
    container_name: gitlab-ai-agent
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - ai-reviewer
    restart: unless-stopped

networks:
  ai-reviewer:
    driver: bridge
